os:
- linux
- osx

sudo: false

language: rust

rust:
- 1.13.0
- stable
- beta

install:
- rustc -Vv
- cargo -V

script:
- cargo build --verbose
- RUST_BACKTRACE=full cargo test --verbose -- --nocapture

cache:
  cargo: true
